views.py
import functools
from formularios import formularioMensaje
from flask import Flask, render_template, blueprints, request, redirect, url_for,session, flash, send_file
from werkzeug.security import check_password_hash, generate_password_hash
from db import get_db




main= blueprints.Blueprint('main', __name__)


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if 'usuario' not in session:
            return redirect(url_for('main.login'))
        return view(**kwargs)

    return wrapped_view

#Inicio de seccion,login y Registro*****

@main.route( '/' )
def hello_world():
    """Función que maneja la raiz del sitio web.

        Parameters:
        Ninguno

        Returns:
        Plantilla inicio.html

    """

    return render_template('inicio.html')


@main.route('/login/', methods=['GET', 'POST'])
def login():
    """Función que maneja la ruta login.Responde a los métodos GET y POST.

        Parameters:
        Ninguno

        Returns:
        login.html si es invocada con el método GET. 
        Redirecciona a  main.ajax si es invocada con POST y la validación es verdadera.

    """

    if request.method =='POST':

        usuario = request.form['username']
        clave = request.form['userPassword']
        db = get_db()
        #sql = "select * from usuario where usuario = '{0}' and clave= '{1}'".format(usuario, clave)

        user = db.execute('select * from usuario where username = ? ', (usuario,)).fetchone()
        db.commit()
        db.close()
        if user is not None:

            #print(user[4])
            clave = clave + usuario
            
            sw = check_password_hash(user[4], clave)

            if(sw):

                session['nombre'] = user[1]
                session['usuario'] = user[2]
                if user[5] == 0:
                 return redirect(url_for('main.DashboardSuper'))
                elif  user[5] == 1:
                 return redirect(url_for('main.DashboardPiloto'))   
                elif  user[5] == 2:
                 return redirect(url_for('main.DashboardPasajero')) 

        flash('Usuario o clave incorrecto.')
    
    return render_template('login.html')


@main.route('/registro/', methods=['GET', 'POST'])
def registro():
    """Función que maneja la ruta Registro.Responde a los métodos GET y POST.

        Parameters:
        Ninguno

        Returns:
        registro.html si es invocada con el método GET. 
        Crea un usuario en la BD si es invocada con POST, no tiene válidaciones.

    """
   
    if request.method == 'POST' :

        nombre = request.form['nombre']
        usuario = request.form['username']
        correo = request.form['correo']
        clave = request.form['contraseña']
        t_user = "2"
        

        db = get_db()
        #agregar SLAT
        clave = clave + usuario
        clave = generate_password_hash(clave)
        db.execute("insert into usuario ( nombre, username, correo, clave, tipo_user) values( ?, ?, ?, ?, ?)",(nombre, usuario, correo, clave, t_user))
        db.commit()
        db.close()
        flash('Cuenta Creada')
        return redirect(url_for('main.registro'))

    elif  request.method == 'GET':       
        
       return render_template('registro.html')


#******Superusuario********


@main.route('/DashboardSuper/')
@login_required
def DashboardSuper():
    return render_template('DashboardSuper.html')

#********Menu Usuarios********


@main.route('/DashboardSuperUsers/', methods=['GET', 'POST'])
@login_required
def DashboardSuperUsers():
     
    if request.method == 'POST' :

        nombre = request.form['nombre']
        usuario = request.form['username']
        correo = request.form['correo']
        clave = request.form['clave']
        t_user = request.form['tipo_user']
        

        db = get_db()
        #agregar SLAT
        clave = clave + usuario
        clave = generate_password_hash(clave)
        db.execute("insert into usuario ( nombre, username, correo, clave, tipo_user) values( ?, ?, ?, ?, ?)",(nombre, usuario, correo, clave, t_user))
        db.commit()
        db.close()
        flash('Cuenta Creada')
        return redirect(url_for('main.DashboardSuperUsers'))



    elif  request.method == 'GET':       
      
      try:
        datos =[]
        db= get_db()
        cursor= db.cursor()
        sql="SELECT * from  usuario,tipo_usuario where usuario.tipo_user= tipo_usuario.id;"
        cursor.execute(sql)
        datos = cursor.fetchall()
        db.commit()
        db.close()
  
      except Exception as ex:
        return print("mensaje error")        
    
    return render_template('DashboardSuperUsers.html', usuarios = datos)

@main.route('/DashboardSuperUsersDelete/<string:username>')
@login_required
def DashboardSuperUsersDelete(username):
        
    try:
        db= get_db()
        cursor= db.cursor()
       
        cursor.execute('DELETE from usuario where usuario.username = ? ', (username,)).fetchone
        db.commit()
        db.close()
        
            
    except Exception as ex:
        return print("mensaje error")        
    
    return redirect(url_for('main.DashboardSuperUsers'))

@main.route('/DashboardSuperUsersEdit/<id>', methods=['GET','POST'])
@login_required
def get_contact(id):
    db= get_db()
    cursor= db.cursor() 
    cursor.execute('SELECT * from usuario where id = ? ', (id,))
    data=cursor.fetchall()
    db.commit()
    db.close()
    #print(data)
    return  render_template('DashboardSuperUsersUpdate.html', usuario = data[0])
    


@main.route('/DashboardSuperUsersUpdate/', methods=['POST','GET'])
@login_required
def DashboardSuperUsersUpdate():
    if request.method == 'POST':
     id= request.form['id']
     nombre = request.form['nombre']
     usuario = request.form['username']
     correo = request.form['correo']
     clave = request.form['clave']
     t_user = request.form['tipo_user']
     db = get_db()
     #agregar SLAT
     clave = clave + usuario
     clave = generate_password_hash(clave)
     db.execute("UPDATE usuario SET(nombre, username, correo, clave, tipo_user) values( ?, ?, ?, ?, ?, ?)",(nombre, usuario, correo, clave, t_user))
            
     db.commit()
     db.close()
     flash('Cuenta Actualizada')
     return redirect(url_for('main.DashboardSuperUsersEdit'))

#****Menu Vuelos********

@main.route('/DashboardSuperVuelos/', methods=['GET', 'POST'])
@login_required
def DashboardSuperVuelos():
     
    if request.method == 'POST' :
        
        fecha = request.form['fecha']
        hora = request.form['hora']
        origen = request.form['origen']
        destino = request.form['destino']
        piloto = request.form['id_piloto']
        avion= request.form['avion']
        capacidad=request.form['capacidad']
        estado=request.form['estado']

        db = get_db()
                  # "insert into usuario ( nombre, username, correo, clave, tipo_user) values( ?, ?, ?, ?, ?)",(nombre, usuario, correo, clave, t_user))
        db.execute("insert into vuelos ( fecha, hora, c_origen, c_destino, t_piloto, avion, capacidad, t_estados) values( ?, ?, ?, ?, ?, ?, ?, ?)",(fecha, hora, origen, destino, piloto, avion, capacidad, estado))
        db.commit()
        db.close()
        flash('Cuenta Creada')
        return redirect(url_for('main.DashboardSuperVuelos'))



    elif  request.method == 'GET':       
      
      try:
        datos =[]
        db= get_db()
        cursor= db.cursor()
        sql="Select fecha,hora,c_origen,c_destino,usuario.nombre as piloto,avion,capacidad,estados.nombre As Estado from usuario,vuelos,estados where vuelos.t_piloto=usuario.id and vuelos.t_estados=estados.id;"
        cursor.execute(sql)
        dvuelo = cursor.fetchall()
        print(dvuelo)
        
  
      except Exception as ex:
        return print("mensaje error")        
    
    return render_template('DashboardSuperVuelos.html', vuelos = dvuelo)
"""
@main.route('/DashboardSuperVuelosDelete/<id>')
@login_required
def DashboardSuperVuelosDelete(id):
        
    try:
        db= get_db()
        cursor= db.cursor()
       
        cursor.execute('DELETE from vuelos where vuelos.id = ? ', (id,)).fetchone
        db.commit()
        db.close()
        
            
    except Exception as ex:
        return print("mensaje error")        
    
    return redirect(url_for('main.DashboardSuperVuelos'))

@main.route('/DashboardSuperUsersEdit/<id>', methods=['GET','POST'])
@login_required
def get_contact(id):
    db= get_db()
    cursor= db.cursor() 
    cursor.execute('SELECT * from usuario where id = ? ', (id,))
    data=cursor.fetchall()
    db.commit()
    db.close()
    #print(data)
    return  render_template('DashboardSuperUsersUpdate.html', usuario = data[0])
    


@main.route('/DashboardSuperUsersUpdate/', methods=['POST','GET'])
@login_required
def DashboardSuperUsersUpdate():
    if request.method == 'POST':
     id= request.form['id']
     nombre = request.form['nombre']
     usuario = request.form['username']
     correo = request.form['correo']
     clave = request.form['clave']
     t_user = request.form['tipo_user']
     db = get_db()
     #agregar SLAT
     clave = clave + usuario
     clave = generate_password_hash(clave)
     db.execute("UPDATE usuario SET(nombre, username, correo, clave, tipo_user) values( ?, ?, ?, ?, ?, ?)",(nombre, usuario, correo, clave, t_user))
            
     db.commit()
     db.close()
     flash('Cuenta Actualizada')
     return redirect(url_for('main.DashboardSuperUsersEdit'))

"""
    
#/DashboardSuperVuelosEdit/    

#***********Menu Reserva********

templates/DashboardPilotoVuelos.html
{%  extends "baseSuperUsers.html" %}
 
{% block contenido %}
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        
                    </div>
                    <div class="cardHeader">
                        
                    </div>
                     
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Vuelos Programados</h2>
                    </div>
                     <table>
                        <thead>
                            <tr>
                                <td>Fecha</td>
                                <td>Hora</td>
                                <td>Origen</td>
                                <td>Destino</td>
                                <td>Piloto</td>
                                <td>Avion</td>
                                <td>Capacidad</td>
                                <td>Estado</td>
                                <td>Operacion</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for vuelo in vuelos %}
                            <tr>
                                <td>{{vuelo.0}}</td>
                                <td>{{vuelo.1}}</td>
                                <td>{{vuelo.2}}</td>
                                <td>{{vuelo.3}}</td>
                                <td>{{vuelo.4}}</td>
                                <td>{{vuelo.5}}</td>
                                <td>{{vuelo.6}}</td>
                                <td>{{vuelo.7}}</td>
                                <td><a href="/DashboardSuperVuelosEdit/{{vuelos.0}}"><ion-icon name="create-outline"></ion-icon>Editar</a></td>
                                <td><a href="/DashboardSuperVuelosDelete/{{vuelos.0}}"><ion-icon name="trash-outline"></ion-icon>Borrar</a></td>
                            </tr>
                            {% endfor %}
                                                      
                        </tbody>
                     </table>
                    </div>
                </div>
             </div>   
    {% endblock %}

templates/DashboardSuper.html
{%  extends "baseSuper.html" %}
 
{% block contenido %}
    
   	<li>
	  <a href="{{url_for('main.DashboardSuper')}}">
		<span class="icon"><ion-icon name="accessibility-outline"></ion-icon></span>
		<span class="title">Perfil SuperUsuario</span>
	  </a>
	</li>
	<li>
	<a href="{{url_for('main.DashboardSuperUsers')}}">
		<span class="icon"><ion-icon name="people-outline"></ion-icon></span>
		<span class="title">Usuarios</span>
	  </a>
	</li>
	<li>
	  <a href="{{url_for('main.DashboardSuperVuelos')}}">
		<span class="icon"><ion-icon name="paper-plane-outline"></ion-icon></span>
		<span class="title">Vuelos</span>
	  </a>
	</li>
	<li>
		<a href="{{url_for('main.DashboardSuperReserva')}}">
		  <span class="icon"><ion-icon name="paper-plane-outline"></ion-icon></span>
		  <span class="title">Reservas</span>
		</a>
	  </li>
	<li> 
	  <a href="{{url_for('main.DashboardSuperValoracion')}}">
		<span class="icon"><ion-icon name="chatbubble-ellipses-outline"></ion-icon></span>
		<span class="title">Valoraciones</span>
	  </a>
	</li>
	<li>
	  <a href="#">
	   <span class="icon"><ion-icon name="lock-closed-outline"></ion-icon></span>
	   <span class="title">Contraseña</span>
	  </a>
	</li>
	<li>
	   <a href="{{url_for('main.logout')}}">
		<span class="icon"><ion-icon name="log-out-outline"></ion-icon></span>
		<span class="title">Salir</span>
     </a>
	</li>

{% endblock %}

templates/DashboardSuperReserva.html
{%  extends "baseSuperUsers.html" %}
 
{% block contenido %}
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Hacer Reservas</h2>
                    </div>
                    <div class="cardHeader">
                        <form action ="{{url_for('main.DashboardSuperUsers')}}" method="POST">
                        <input type="text" name="nombre" placeholder="Nombre Completo">
                        <input type="text" name="username" placeholder="Nombre Usuario">
                        <input type="email" name="correo" placeholder="Correo Electronico">
                        <input type="password" name="clave" placeholder="Contraseña"> 
                        <input type="text" name="tipo_user" placeholder="Tipo de Usuario"> 
                        <button class="form__button" value="Enviar" type="submit">Guardar</button>
                    </div>
                     
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Vuelos Reservados</h2>
                    </div>
                     <table>
                        <thead>
                            <tr>
                                <td>Origen</td>
                                <td>Destino</td>
                                <td>Capacidad</td>
                                <td>Avion</td>
                               
                                <td>Estado</td>                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for reserva in reservas %}
                            <tr>
                                <td>{{reserva.0}}</td>
                                <td>{{reserva.1}}</td>
                                <td>{{reserva.2}}</td>
                                <td>{{reserva.3}}</td>
                                <td>{{reserva.4}}</td>
                                <td>{{reserva.5}}</td>
                                <td>{{reserva.6}}</td>
                                <td>{{reserva.7}}</td>
                                <td><a href="/DashboardSuperUsersEdit/{{reservas.1}}"><ion-icon name="create-outline"></ion-icon></a></td>
                                <td><a href="/DashboardSuperVuelosDelete/{{reservas.1}}"><ion-icon name="trash-outline"></ion-icon></a></td>
                            </tr>
                            {% endfor %}
                                                      
                        </tbody>
                     </table>
                    </div>
                </div>
             </div>   
    {% endblock %}

templates/DashboardSuperUsersDelete.html
{%  extends "baseSuperUsers.html" %}
 
{% block contenido %}
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Crear Usuarios</h2>
                    </div>
                    <div class="cardHeader">
                        <form action ="{{url_for('main.DashboardSuperUsers')}}" method="POST">
                        <input type="text" name="nombre" placeholder="Nombre Completo">
                        <input type="text" name="username" placeholder="Nombre Usuario">
                        <input type="email" name="correo" placeholder="Correo Electronico">
                        <input type="password" name="clave" placeholder="Contraseña"> 
                        <input type="text" name="tipo_user" placeholder="Tipo de Usuario"> 
                        <button class="form__button" value="Enviar" type="submit">Guardar</button>
                    </div>
                     
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Usuarios</h2>
                    </div>
                     <table>
                        <thead>
                            <tr>
                                <td>Nombre</td>
                                <td>Username</td>
                                <td>Correo</td>
                                <td>Tipo</td>
                                <td>Operacion</td>                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for usuario in usuarios %}
                            <tr>
                                <td>{{ usuario.0}}</td>
                                <td>{{ usuario.1}}</td>
                                <td>{{ usuario.2}}</td>
                                <td>{{ usuario.3}}</td>
                                <td>{{ usuario.4}}</td>
                                <td>
                                    <a href="/edit/"><ion-icon name="pencil-outline"></ion-icon></a>
                                </td>
                                <td>
                                    <a href="/DashboardSuperUsersDelete/{{usuario.0}}"><ion-icon name="trash-outline"></ion-icon></a>
                                </td>
                            </tr>
                            {% endfor %}
                                                      
                        </tbody>
"""
                     </table>
                    </div>
                </div>
             </div>   
    {% endblock %}

templates/DashboardSuperValoracion.html
{%  extends "baseSuperUsers.html" %}
 
{% block contenido %}
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Hacer Reservas</h2>
                    </div>
                    <div class="cardHeader">
                        <form action ="{{url_for('main.DashboardSuperUsers')}}" method="POST">
                        <input type="text" name="nombre" placeholder="Nombre Completo">
                        <input type="text" name="username" placeholder="Nombre Usuario">
                        <input type="email" name="correo" placeholder="Correo Electronico">
                        <input type="password" name="clave" placeholder="Contraseña"> 
                        <input type="text" name="tipo_user" placeholder="Tipo de Usuario"> 
                        <button class="form__button" value="Enviar" type="submit">Guardar</button>
                    </div>
                     
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Vuelos Reservados</h2>
                    </div>
                     <table>
                        <thead>
                            <tr>
                                <td>Origen</td>
                                <td>Destino</td>
                                <td>Capacidad</td>
                                <td>Avion</td>
                               
                                <td>Estado</td>                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for reserva in reservas %}
                            <tr>
                                <td>{{reserva.0}}</td>
                                <td>{{reserva.1}}</td>
                                <td>{{reserva.2}}</td>
                                <td>{{reserva.3}}</td>
                                <td>{{reserva.4}}</td>
                                <td>{{reserva.5}}</td>
                                <td>{{reserva.6}}</td>
                                <td>{{reserva.7}}</td>
                                <td><a href="/DashboardSuperUsersEdit/{{reservas.1}}"><ion-icon name="create-outline"></ion-icon></a></td>
                                <td><a href="/DashboardSuperVuelosDelete/{{reservas.1}}"><ion-icon name="trash-outline"></ion-icon></a></td>
                            </tr>
                            {% endfor %}
                                                      
                        </tbody>
                     </table>
                    </div>
                </div>
             </div>   
    {% endblock %}

templates/DashboardSuperVuelos.html
{%  extends "baseSuperUsers.html" %}
 
{% block contenido %}
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Crear Vuelos</h2>
                    </div>
                    <div class="cardHeader">
                        <form action ="{{url_for('main.DashboardSuperVuelos')}}" method="POST">
                        <input type="text" name="fecha" placeholder="Fecha">
                        <input type="text" name="hora" placeholder="Hora">
                        <input type="text" name="origen" placeholder="Origen"> 
                        <input type="text" name="destino" placeholder="Destino"> 
                        <input type="text" name="id_piloto" placeholder="Piloto">
                        <input type="text" name="avion" placeholder="Avion">
                        <input type="text" name="capacidad" placeholder="Capacidad">
                        <input type="text" name="estado" placeholder="estado">
                        <button class="form__button" value="Enviar" type="submit
                        ">Guardar</button>
                    </div>
                     
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Vuelos Programados</h2>
                    </div>
                     <table>
                        <thead>
                            <tr>
                                <td>Fecha</td>
                                <td>Hora</td>
                                <td>Origen</td>
                                <td>Destino</td>
                                <td>Piloto</td>
                                <td>Avion</td>
                                <td>Capacidad</td>
                                <td>Estado</td>
                                <td>Operacion</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for vuelo in vuelos %}
                            <tr>
                                <td>{{vuelo.0}}</td>
                                <td>{{vuelo.1}}</td>
                                <td>{{vuelo.2}}</td>
                                <td>{{vuelo.3}}</td>
                                <td>{{vuelo.4}}</td>
                                <td>{{vuelo.5}}</td>
                                <td>{{vuelo.6}}</td>
                                <td>{{vuelo.7}}</td>
                                <td><a href="/DashboardSuperVuelosEdit/{{vuelos.0}}"><ion-icon name="create-outline"></ion-icon>Editar</a></td>
                                <td><a href="/DashboardSuperVuelosDelete/{{vuelos.0}}"><ion-icon name="trash-outline"></ion-icon>Borrar</a></td>
                            </tr>
                            {% endfor %}
                                                      
                        </tbody>
                     </table>
                    </div>
                </div>
             </div>   
    {% endblock %}

templates/DashboardSuperVuelosDelete.html
{%  extends "baseSuperUsers.html" %}
 
{% block contenido %}
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Crear Vuelos</h2>
                    </div>
                    <div class="cardHeader">
                        <form action ="{{url_for('main.DashboardSuperVuelosDelete')}}" method="POST">
                        <input type="text" name="id" placeholder="Id">
                        <input type="text" name="fecha" placeholder="Fecha">
                        <input type="text" name="hora" placeholder="Hora">
                        <input type="text" name="origen" placeholder="Origen"> 
                        <input type="text" name="destino" placeholder="Destino"> 
                        <input type="text" name="id_piloto" placeholder="Piloto">
                        <input type="text" name="avion" placeholder="Avion">
                        <input type="text" name="capacidad" placeholder="Capacidad">
                        <input type="text" name="estado" placeholder="estado">
                        <button class="form__button" value="Enviar" type="submit
                        ">Guardar</button>
                    </div>
                     
            <div class="details">
                <!-- order details list -->
                <div class="recentOrders">
                    <div class="cardHeader">
                        <h2>Vuelos Programados</h2>
                    </div>
                     <table>
                        <thead>
                            <tr>
                                <td>Id</td>
                                <td>Fecha</td>
                                <td>Hora</td>
                                <td>Origen</td>
                                <td>Piloto</td>
                                <td>Avion</td>
                                <td>Capacidad</td>
                                <td>Estado</td>                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for vuelo in vuelos %}
                            <tr>
                                <td>{{vuelo.0}}</td>
                                <td>{{vuelo.1}}</td>
                                <td>{{vuelo.2}}</td>
                                <td>{{vuelo.3}}</td>
                                <td>{{vuelo.4}}</td>
                                <td>{{vuelo.5}}</td>
                                <td>{{vuelo.6}}</td>
                                <td>{{vuelo.7}}</td>
                                <td><a href="/DashboardSuperVuelosEdit/{{vuelos.1}}"><ion-icon name="create-outline"></ion-icon></a></td>
                                <td><a href="/DashboardSuperVuelosDelete/{{vuelos.1}}"><ion-icon name="trash-outline"></ion-icon></a></td>
                            </tr>
                            {% endfor %}
                                                      
                        </tbody>
                     </table>
                    </div>
                </div>
             </div>   
    {% endblock %}

templates/base1.html
<!DOCTYPE html>
<title>{% block title %}{% endblock %} Bienvenido </title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/miEstilo.css') }}" />
<nav>
    <h1>Bienvenido</h1>
    <ul>
        {% if g.user %}
        <li>
            <a class="action" href="{{ url_for('downloadpdf') }}">Descargar doc pdf</a
      >
    </li>
    <li>
      <a class="action" href="{{ url_for('downloadimage') }}"
        >Descargar imagen</a
      >
    </li>
    <li><a href="{{ url_for('logout') }}">Cerrar Sesión</a> {% else %}</li>

        <li><a href="{{ url_for('register') }}">Registrarse</a></li>
        <li><a href="{{ url_for('login') }}">Iniciar Sesión</a> {% endif %}</li>

        
    </ul>
</nav>
<section class="content">
    <header>{% block header %}{% endblock %}</header>
    {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
    {% endfor %} {% block content %}{% endblock %}
</section>

templates/base2.html
<html>
   <head>
       <script src="{{ url_for('static', filename='js/funciones.js') }}"></script>
       <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/mioCSS.css') }}" />
	   <title>{% block titulo %} {% endblock %}</title>
	   <meta charset="UTF-8"/>
      <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png')}}"/>
   </head>
   <body>
    <h1>Esta es la empresa número 1 en servicios</h1>
    <p>Nombre: {{session['nombre']}}</p>
      <p>Usuario: {{session['usuario']}}</p>

      <p><a href="{{url_for('main.logout')}}">Salir</a></p>
      
    {% for mensaje in get_flashed_messages() %}

      <div class="error">{{ mensaje }}</div>

    {% endfor %}
    
    {% block contenido %} {% endblock %}

    
      
   </body>
</html>